### PR TITLE
spec-checking-fn: add missing static dispatches, refactoring to match…

### LINKED ISSUE #53: After patching implementation, multi-arity functions that have a spec/fdef breaks
I encountered the real life use case and described it here: https://github.com/bhb/expound/issues/197
The minimal reproduction case is here: https://github.com/raymond-w-ko/spec-arity-repro
Run it by:
```
> npm install
> make watch
> # switch to another terminal
> node
>> const m = require("./handler"); m.handler();
```

Error:
```
Uncaught:
TypeError: playbox.fake_expound_str.cljs$core$IFn$_invoke$arity$2 is not a function
    at Object.playbox$handler (/home/rko/src/spec-arity-repro/cljs-runtime/playbox.cljs:29:3)
at Object.playbox$test_fn [as test_fn] (/home/rko/src/spec-arity-repro/cljs-runtime/playbox.cljs:25:3)
```

### PR DESCRIPTION
**Pull request by raymond-w-ko**
… original more

This appears to fix #53. This biggest change is that it sets up "static dispatches" like the original function. I also added some comments to chunks and did some slight refactoring to make it match the original so that it is easier to keep in sync if there are updates.

Was there a reason `setup-static-dispatches` is not used in the current implementation?

### CODE REVIEW

**Comment by jeaye** [comment]
Thanks for the PR! I have no opposition to the changes, but I'll need to spend more time with them and test them outside of my work hours. I'll follow up here after I've done that.

> Was there a reason setup-static-dispatches is not used in the current implementation?

Oversight, probably. This should marginally improve performance, right?

**Comment by raymond-w-ko** [comment]
Oh yeah, here is the original ClojureScript `spec-checking-fn` for reference.
https://github.com/clojure/clojurescript/blob/599cd05fd271b4ce672e8a6124f0f785b1b3b2d0/src/main/cljs/cljs/spec/test/alpha.cljs#L85

**Comment by jeaye** [comment]
Was there a noticeable issue which made you look into Orchestra's implementation? i.e. did you notice that the static dispatches were missing somehow, without seeing the code?

**Comment by raymond-w-ko** [comment]
> Thanks for the PR! I have no opposition to the changes, but I'll need to spend more time with them and test them outside of my work hours. I'll follow up here after I've done that.
> 
> > Was there a reason setup-static-dispatches is not used in the current implementation?
> 
> Oversight, probably. This should marginally improve performance, right?

In my case, it actually is required as that creates the missing internal dispatch functions required

**Comment by raymond-w-ko** [comment]
I was the one who opened #53 as orchestra was breaking for me if I instrument my functions.

**Comment by jeaye** [comment]
Thank you for the PR! This has been deployed as 2020.09.18-1

**Pull request merged**
