### PR TITLE
@jeaye

### PR DESCRIPTION
**Pull request by djtango**
Does this look better?

### CODE REVIEW

**Comment by jeaye** [comment]
Ah, this introduces an issue. The *only* thing which should change is `1.9.0` to `1.9.0-alpha1`. That is, the final line should be:

```clojure
;; Requires 1.9.0-alpha1 >= Clojure < 1.9.0-alpha16
```

We keep the `>=` here because Clojure needs to be at least version `1.9.0-alpha1`, but less than `1.9.0-alpha16`. Make sense?

**Comment by djtango** [comment]
Ok - happy to change it, sorry for generating all this churn!

Am a bit confused though, I read `1.9.0-alpha1 >= Clojure < 1.9.0-alpha16` as:

```
(and (>= '1.9.0-alpha1 'Clojure)
     (< 'Clojure '1.9.0-alpha16))
```    

Which translates to must be less than alpha16 and also less than or equal to alpha1 - I'm guessing I've parsed this wrong?

**Comment by djtango** [comment]
All done

**Comment by jeaye** [comment]
Thank you, @djtango. Sorry for all the confusion!

**Pull request merged**
