### PR TITLE
Support for tools.deps

### PR DESCRIPTION
**Pull request by borkdude**
@jeaye @bhb

This deps.edn file should make co-developing experimental features in orchestra + expound easier, since you can refer to SHAs in feature branches.

It also has the added benefit that orchestra can be used as a git dep in other tools.deps libraries.

### CODE REVIEW

**Comment by jeaye** [comment]
I've sat on this for a few days, thinking about it. To me, adding `deps.edn` complicates things more, given that Orchestra is using leiningen and that's all I intent to use for the foreseeable future. leiningen has its own plugins for pulling down deps by git ref, so those could be used in order to operate with expound's master, for example.

I appreciate that you took the time to suggest this in the form of a PR, especially in conjunction with your help on the CLJS catch up. However, I don't think this will directly benefit users of Orchestra and it goes against my current workflow.

Thank you!

**Comment by borkdude** [comment]
FWIW, I just posted this 10 minutes ago:
https://twitter.com/borkdude/status/1096096934060789768

**Comment by jeaye** [comment]
Most prescient! It does indeed open up another avenue of collaboration, at the cost of an additional `deps.edn` to maintain. My understanding of the ecosystem is the leiningen is still the de facto tool, so asking Clojure devs to operate with it is unlikely to be a huge deterrent. Until the Clojure tooling either reaches parity with leiningen's ecosystem or provides something inaccessible from leiningen, I don't see using it as a clear win.

**Comment by arichiardi** [comment]
Another 2c - this is what I do now in my project: https://github.com/elasticpath/fonda/blob/master/project.clj

basically delegating all the deps to `deps.edn` and using the wonderful `lein-tools-deps`.

**Comment by borkdude** [comment]
@jeaye I don't want to force anything upon you and no hard feelings for closing this. 

It does provide something inaccessible from leiningen. It adds the ability to use this library as a git/dep so you could test individual commits/branches trivially, before making a release to Clojars with leiningen. That's the main reason why I added this file. The minimum deps.edn for this would be:

```
{:paths ["src/clj" "src/cljc" "src/cljs"]
 :aliases
 {:test
  {:extra-paths ["test/clj" "test/cljs" "test/cljc" "cljs-test-runner-out/gen"]
   :extra-deps {
                org.clojure/clojurescript {:mvn/version "1.10.516"}
                expound {:mvn/version "0.7.1"}}}}}
```

Adding a `pom.xml` which you can generate with leiningen would add the same benefit, without the need of having a deps.edn file.

**Comment by borkdude** [comment]
Example of added `pom.xml` in another project that wasn't released to Clojars yet:

https://github.com/borkdude/test.chuck.sfr-cljs/commit/fc826ba5243de496182fa47c771506fc7c03983d

Now I'm able to use this in my tests in a deps.edn project.

**Pull request closed without merging**
